# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-FillInForm-ForceUTF8
version:      0.01
version_from: lib/HTML/FillInForm/ForceUTF8.pm
installdirs:  site
requires:
    Encode:                        0
    HTML::FillInForm:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
